import { Theme, ThemeType } from '@/core/types/theme';

export const THEMES: Record<ThemeType, Theme> = {
  default: {
    id: 'default',
    name: 'Palpitos Original',
    emoji: '💕',
    isPremium: false,
    description: 'El clásico rosa y morado de Palpitos',
    colors: {
      primary: '#FF6B9D',
      secondary: '#C44569',
      accent: '#FFA07A',
      gradientStart: '#667eea',
      gradientEnd: '#764ba2',
      background: '#FFF5F7',
      cardBackground: '#FFFFFF',
      text: '#181113',
      textSecondary: '#6B7280',
      textLight: '#9CA3AF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FF6B9D',
      syncColor: '#C44569',
      chatBackground: '#FFF5F7',
      messageBubbleOwn: '#FF6B9D',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'hearts',
  },
  
  sunset: {
    id: 'sunset',
    name: 'Atardecer',
    emoji: '🌅',
    isPremium: false,
    description: 'Cálidos tonos de atardecer',
    colors: {
      primary: '#FF6B35',
      secondary: '#F7931E',
      accent: '#FDC830',
      gradientStart: '#FF6B35',
      gradientEnd: '#F7931E',
      background: '#FFF8F0',
      cardBackground: '#FFFFFF',
      text: '#2D1B00',
      textSecondary: '#8B6914',
      textLight: '#B8860B',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FF6B35',
      syncColor: '#F7931E',
      chatBackground: '#FFF8F0',
      messageBubbleOwn: '#FF6B35',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'gradient',
  },
  
  ocean: {
    id: 'ocean',
    name: 'Océano',
    emoji: '🌊',
    isPremium: false,
    description: 'Profundidades del mar',
    colors: {
      primary: '#00B4DB',
      secondary: '#0083B0',
      accent: '#4FACFE',
      gradientStart: '#00B4DB',
      gradientEnd: '#0083B0',
      background: '#F0F9FF',
      cardBackground: '#FFFFFF',
      text: '#0C4A6E',
      textSecondary: '#0369A1',
      textLight: '#7DD3FC',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#00B4DB',
      syncColor: '#0083B0',
      chatBackground: '#F0F9FF',
      messageBubbleOwn: '#00B4DB',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'waves',
  },
  
  forest: {
    id: 'forest',
    name: 'Bosque',
    emoji: '🌲',
    isPremium: false,
    description: 'Naturaleza verde y fresca',
    colors: {
      primary: '#11998E',
      secondary: '#38EF7D',
      accent: '#7FFF00',
      gradientStart: '#11998E',
      gradientEnd: '#38EF7D',
      background: '#F0FDF4',
      cardBackground: '#FFFFFF',
      text: '#064E3B',
      textSecondary: '#047857',
      textLight: '#6EE7B7',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#11998E',
      syncColor: '#38EF7D',
      chatBackground: '#F0FDF4',
      messageBubbleOwn: '#11998E',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'dots',
  },
  
  lavender: {
    id: 'lavender',
    name: 'Lavanda',
    emoji: '💜',
    isPremium: false,
    description: 'Suave y relajante',
    colors: {
      primary: '#A78BFA',
      secondary: '#8B5CF6',
      accent: '#C084FC',
      gradientStart: '#A78BFA',
      gradientEnd: '#8B5CF6',
      background: '#FAF5FF',
      cardBackground: '#FFFFFF',
      text: '#4C1D95',
      textSecondary: '#6D28D9',
      textLight: '#C4B5FD',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#A78BFA',
      syncColor: '#8B5CF6',
      chatBackground: '#FAF5FF',
      messageBubbleOwn: '#A78BFA',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'dots',
  },
  
  trap: {
    id: 'trap',
    name: 'Real Hasta La Muerte',
    emoji: '👑',
    isPremium: false,
    description: 'Estilo urbano trap - Negro, rojo y blanco',
    colors: {
      primary: '#FF0000',
      secondary: '#8B0000',
      accent: '#FF4500',
      gradientStart: '#FF0000',
      gradientEnd: '#8B0000',
      background: '#0A0A0A',
      cardBackground: '#1C1C1C',
      text: '#FFFFFF',
      textSecondary: '#FF0000',
      textLight: '#CCCCCC',
      success: '#10B981',
      warning: '#FF4500',
      error: '#FF0000',
      info: '#FF4500',
      heartColor: '#FF0000',
      syncColor: '#8B0000',
      chatBackground: '#0A0A0A',
      messageBubbleOwn: '#FF0000',
      messageBubblePartner: '#1C1C1C',
    },
    chatBackgroundPattern: 'none',
  },
  
  // TEMAS PREMIUM
  
  cherry: {
    id: 'cherry',
    name: 'Cereza',
    emoji: '🍒',
    isPremium: true,
    description: 'Rojo intenso y apasionado',
    colors: {
      primary: '#E11D48',
      secondary: '#BE123C',
      accent: '#FB7185',
      gradientStart: '#E11D48',
      gradientEnd: '#BE123C',
      background: '#FFF1F2',
      cardBackground: '#FFFFFF',
      text: '#881337',
      textSecondary: '#9F1239',
      textLight: '#FDA4AF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#E11D48',
      syncColor: '#BE123C',
      chatBackground: '#FFF1F2',
      messageBubbleOwn: '#E11D48',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'hearts',
  },
  
  midnight: {
    id: 'midnight',
    name: 'Medianoche',
    emoji: '🌙',
    isPremium: true,
    description: 'Oscuro y misterioso',
    colors: {
      primary: '#1E3A8A',
      secondary: '#1E293B',
      accent: '#3B82F6',
      gradientStart: '#1E3A8A',
      gradientEnd: '#1E293B',
      background: '#0F172A',
      cardBackground: '#1E293B',
      text: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textLight: '#94A3B8',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#3B82F6',
      syncColor: '#1E3A8A',
      chatBackground: '#0F172A',
      messageBubbleOwn: '#1E3A8A',
      messageBubblePartner: '#1E293B',
    },
    chatBackgroundPattern: 'stars',
  },
  
  peach: {
    id: 'peach',
    name: 'Durazno',
    emoji: '🍑',
    isPremium: true,
    description: 'Dulce y delicado',
    colors: {
      primary: '#FB923C',
      secondary: '#F97316',
      accent: '#FDBA74',
      gradientStart: '#FB923C',
      gradientEnd: '#F97316',
      background: '#FFF7ED',
      cardBackground: '#FFFFFF',
      text: '#7C2D12',
      textSecondary: '#9A3412',
      textLight: '#FED7AA',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FB923C',
      syncColor: '#F97316',
      chatBackground: '#FFF7ED',
      messageBubbleOwn: '#FB923C',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'gradient',
  },
  
  galaxy: {
    id: 'galaxy',
    name: 'Galaxia',
    emoji: '🌌',
    isPremium: true,
    description: 'Espacio profundo y estrellas',
    colors: {
      primary: '#8B5CF6',
      secondary: '#6366F1',
      accent: '#EC4899',
      gradientStart: '#8B5CF6',
      gradientEnd: '#EC4899',
      background: '#1E1B4B',
      cardBackground: '#312E81',
      text: '#F5F3FF',
      textSecondary: '#DDD6FE',
      textLight: '#C4B5FD',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#EC4899',
      syncColor: '#8B5CF6',
      chatBackground: '#1E1B4B',
      messageBubbleOwn: '#8B5CF6',
      messageBubblePartner: '#312E81',
    },
    chatBackgroundPattern: 'stars',
  },
  
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    emoji: '🌈',
    isPremium: true,
    description: 'Luces del norte mágicas',
    colors: {
      primary: '#06B6D4',
      secondary: '#8B5CF6',
      accent: '#10B981',
      gradientStart: '#06B6D4',
      gradientEnd: '#8B5CF6',
      background: '#F0FDFA',
      cardBackground: '#FFFFFF',
      text: '#134E4A',
      textSecondary: '#0F766E',
      textLight: '#5EEAD4',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#06B6D4',
      syncColor: '#8B5CF6',
      chatBackground: '#F0FDFA',
      messageBubbleOwn: '#06B6D4',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'waves',
  },
  
  sakura: {
    id: 'sakura',
    name: 'Sakura',
    emoji: '🌸',
    isPremium: true,
    description: 'Flores de cerezo japonesas',
    colors: {
      primary: '#F9A8D4',
      secondary: '#EC4899',
      accent: '#FDE68A',
      gradientStart: '#F9A8D4',
      gradientEnd: '#EC4899',
      background: '#FDF2F8',
      cardBackground: '#FFFFFF',
      text: '#831843',
      textSecondary: '#9F1239',
      textLight: '#FBCFE8',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#F9A8D4',
      syncColor: '#EC4899',
      chatBackground: '#FDF2F8',
      messageBubbleOwn: '#F9A8D4',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'dots',
  },
  
  neon: {
    id: 'neon',
    name: 'Neón',
    emoji: '⚡',
    isPremium: true,
    description: 'Cyberpunk vibrante',
    colors: {
      primary: '#FF00FF',
      secondary: '#00FFFF',
      accent: '#FFFF00',
      gradientStart: '#FF00FF',
      gradientEnd: '#00FFFF',
      background: '#0A0A0A',
      cardBackground: '#1A1A1A',
      text: '#FFFFFF',
      textSecondary: '#00FFFF',
      textLight: '#FF00FF',
      success: '#00FF00',
      warning: '#FFFF00',
      error: '#FF0000',
      info: '#00FFFF',
      heartColor: '#FF00FF',
      syncColor: '#00FFFF',
      chatBackground: '#0A0A0A',
      messageBubbleOwn: '#FF00FF',
      messageBubblePartner: '#1A1A1A',
    },
    chatBackgroundPattern: 'none',
  },
  
  desert: {
    id: 'desert',
    name: 'Desierto',
    emoji: '🏜️',
    isPremium: true,
    description: 'Cálido atardecer del desierto',
    colors: {
      primary: '#F59E0B',
      secondary: '#D97706',
      accent: '#FCD34D',
      gradientStart: '#F59E0B',
      gradientEnd: '#DC2626',
      background: '#FFFBEB',
      cardBackground: '#FFFFFF',
      text: '#78350F',
      textSecondary: '#92400E',
      textLight: '#FDE68A',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#F59E0B',
      syncColor: '#D97706',
      chatBackground: '#FFFBEB',
      messageBubbleOwn: '#F59E0B',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'gradient',
  },
};

// Temas gratuitos
export const FREE_THEMES: ThemeType[] = ['default', 'sunset', 'ocean', 'forest', 'lavender', 'trap'];

// Temas premium
export const PREMIUM_THEMES: ThemeType[] = [
  'cherry',
  'midnight',
  'peach',
  'galaxy',
  'aurora',
  'sakura',
  'neon',
  'desert',
];
