import { Theme, ThemeType } from '@/core/types/theme';

export const THEMES: Record<ThemeType, Theme> = {
  default: {
    id: 'default',
    name: 'Palpitos Original',
    emoji: '💕',
    isPremium: false,
    description: 'El clásico rosa y morado de Palpitos',
    colors: {
      primary: '#FF1493',
      secondary: '#DC143C',
      accent: '#FF69B4',
      gradientStart: '#7B68EE',
      gradientEnd: '#9370DB',
      background: '#FFF5F7',
      cardBackground: '#FFFFFF',
      text: '#181113',
      textSecondary: '#6B7280',
      textLight: '#9CA3AF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FF1493',
      syncColor: '#DC143C',
      chatBackground: '#FFF5F7',
      messageBubbleOwn: '#FF1493',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'hearts',
  },
  
  sunset: {
    id: 'sunset',
    name: 'Atardecer',
    emoji: '🌅',
    isPremium: false,
    description: 'Cálidos tonos de atardecer',
    colors: {
      primary: '#FF4500',
      secondary: '#FF8C00',
      accent: '#FFD700',
      gradientStart: '#FF4500',
      gradientEnd: '#FF8C00',
      background: '#FFF8F0',
      cardBackground: '#FFFFFF',
      text: '#2D1B00',
      textSecondary: '#8B6914',
      textLight: '#B8860B',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FF4500',
      syncColor: '#FF8C00',
      chatBackground: '#FFF8F0',
      messageBubbleOwn: '#FF4500',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'gradient',
  },
  
  ocean: {
    id: 'ocean',
    name: 'Océano',
    emoji: '🌊',
    isPremium: false,
    description: 'Profundidades del mar',
    colors: {
      primary: '#00CED1',
      secondary: '#1E90FF',
      accent: '#00BFFF',
      gradientStart: '#00CED1',
      gradientEnd: '#1E90FF',
      background: '#F0F9FF',
      cardBackground: '#FFFFFF',
      text: '#0C4A6E',
      textSecondary: '#0369A1',
      textLight: '#7DD3FC',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#00CED1',
      syncColor: '#1E90FF',
      chatBackground: '#F0F9FF',
      messageBubbleOwn: '#00CED1',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'waves',
  },
  
  forest: {
    id: 'forest',
    name: 'Bosque',
    emoji: '🌲',
    isPremium: false,
    description: 'Naturaleza verde y fresca',
    colors: {
      primary: '#00C853',
      secondary: '#00E676',
      accent: '#76FF03',
      gradientStart: '#00C853',
      gradientEnd: '#00E676',
      background: '#F0FDF4',
      cardBackground: '#FFFFFF',
      text: '#064E3B',
      textSecondary: '#047857',
      textLight: '#6EE7B7',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#00C853',
      syncColor: '#00E676',
      chatBackground: '#F0FDF4',
      messageBubbleOwn: '#00C853',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'dots',
  },
  
  lavender: {
    id: 'lavender',
    name: 'Lavanda',
    emoji: '💜',
    isPremium: false,
    description: 'Suave y relajante',
    colors: {
      primary: '#9C27B0',
      secondary: '#7B1FA2',
      accent: '#BA68C8',
      gradientStart: '#9C27B0',
      gradientEnd: '#7B1FA2',
      background: '#FAF5FF',
      cardBackground: '#FFFFFF',
      text: '#4C1D95',
      textSecondary: '#6D28D9',
      textLight: '#C4B5FD',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#9C27B0',
      syncColor: '#7B1FA2',
      chatBackground: '#FAF5FF',
      messageBubbleOwn: '#9C27B0',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'dots',
  },
  
  trap: {
    id: 'trap',
    name: 'Real Hasta La Muerte',
    emoji: '👑',
    isPremium: false,
    description: 'Estilo urbano trap - Negro, rojo y blanco',
    colors: {
      primary: '#FF0000',
      secondary: '#8B0000',
      accent: '#FF4500',
      gradientStart: '#FF0000',
      gradientEnd: '#8B0000',
      background: '#0A0A0A',
      cardBackground: '#1C1C1C',
      text: '#FFFFFF',
      textSecondary: '#FF0000',
      textLight: '#CCCCCC',
      success: '#10B981',
      warning: '#FF4500',
      error: '#FF0000',
      info: '#FF4500',
      heartColor: '#FF0000',
      syncColor: '#8B0000',
      chatBackground: '#0A0A0A',
      messageBubbleOwn: '#FF0000',
      messageBubblePartner: '#1C1C1C',
    },
    chatBackgroundPattern: 'none',
  },
  
  // TEMAS PREMIUM
  
  cherry: {
    id: 'cherry',
    name: 'Cereza',
    emoji: '🍒',
    isPremium: true,
    description: 'Rojo intenso y apasionado',
    colors: {
      primary: '#DC143C',
      secondary: '#B22222',
      accent: '#FF6347',
      gradientStart: '#DC143C',
      gradientEnd: '#B22222',
      background: '#FFF1F2',
      cardBackground: '#FFFFFF',
      text: '#881337',
      textSecondary: '#9F1239',
      textLight: '#FDA4AF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#DC143C',
      syncColor: '#B22222',
      chatBackground: '#FFF1F2',
      messageBubbleOwn: '#DC143C',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'hearts',
  },
  
  midnight: {
    id: 'midnight',
    name: 'Medianoche',
    emoji: '🌙',
    isPremium: true,
    description: 'Oscuro y misterioso',
    colors: {
      primary: '#1E3A8A',
      secondary: '#1E293B',
      accent: '#3B82F6',
      gradientStart: '#1E3A8A',
      gradientEnd: '#1E293B',
      background: '#0F172A',
      cardBackground: '#1E293B',
      text: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textLight: '#94A3B8',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#3B82F6',
      syncColor: '#1E3A8A',
      chatBackground: '#0F172A',
      messageBubbleOwn: '#1E3A8A',
      messageBubblePartner: '#1E293B',
    },
    chatBackgroundPattern: 'stars',
  },
  
  peach: {
    id: 'peach',
    name: 'Durazno',
    emoji: '🍑',
    isPremium: true,
    description: 'Dulce y delicado',
    colors: {
      primary: '#FF7F50',
      secondary: '#FF6347',
      accent: '#FFA07A',
      gradientStart: '#FF7F50',
      gradientEnd: '#FF6347',
      background: '#FFF7ED',
      cardBackground: '#FFFFFF',
      text: '#7C2D12',
      textSecondary: '#9A3412',
      textLight: '#FED7AA',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FF7F50',
      syncColor: '#FF6347',
      chatBackground: '#FFF7ED',
      messageBubbleOwn: '#FF7F50',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'gradient',
  },
  
  galaxy: {
    id: 'galaxy',
    name: 'Galaxia',
    emoji: '🌌',
    isPremium: true,
    description: 'Espacio profundo y estrellas',
    colors: {
      primary: '#9370DB',
      secondary: '#6A5ACD',
      accent: '#FF1493',
      gradientStart: '#9370DB',
      gradientEnd: '#FF1493',
      background: '#1E1B4B',
      cardBackground: '#312E81',
      text: '#F5F3FF',
      textSecondary: '#DDD6FE',
      textLight: '#C4B5FD',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FF1493',
      syncColor: '#9370DB',
      chatBackground: '#1E1B4B',
      messageBubbleOwn: '#9370DB',
      messageBubblePartner: '#312E81',
    },
    chatBackgroundPattern: 'stars',
  },
  
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    emoji: '🌈',
    isPremium: true,
    description: 'Luces del norte mágicas',
    colors: {
      primary: '#00CED1',
      secondary: '#9370DB',
      accent: '#00FA9A',
      gradientStart: '#00CED1',
      gradientEnd: '#9370DB',
      background: '#F0FDFA',
      cardBackground: '#FFFFFF',
      text: '#134E4A',
      textSecondary: '#0F766E',
      textLight: '#5EEAD4',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#00CED1',
      syncColor: '#9370DB',
      chatBackground: '#F0FDFA',
      messageBubbleOwn: '#00CED1',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'waves',
  },
  
  sakura: {
    id: 'sakura',
    name: 'Sakura',
    emoji: '🌸',
    isPremium: true,
    description: 'Flores de cerezo japonesas',
    colors: {
      primary: '#FF69B4',
      secondary: '#FF1493',
      accent: '#FFD700',
      gradientStart: '#FF69B4',
      gradientEnd: '#FF1493',
      background: '#FDF2F8',
      cardBackground: '#FFFFFF',
      text: '#831843',
      textSecondary: '#9F1239',
      textLight: '#FBCFE8',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FF69B4',
      syncColor: '#FF1493',
      chatBackground: '#FDF2F8',
      messageBubbleOwn: '#FF69B4',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'dots',
  },
  
  neon: {
    id: 'neon',
    name: 'Neón',
    emoji: '⚡',
    isPremium: true,
    description: 'Cyberpunk vibrante',
    colors: {
      primary: '#FF00FF',
      secondary: '#00FFFF',
      accent: '#FFFF00',
      gradientStart: '#FF00FF',
      gradientEnd: '#00FFFF',
      background: '#0A0A0A',
      cardBackground: '#1A1A1A',
      text: '#FFFFFF',
      textSecondary: '#00FFFF',
      textLight: '#FF00FF',
      success: '#00FF00',
      warning: '#FFFF00',
      error: '#FF0000',
      info: '#00FFFF',
      heartColor: '#FF00FF',
      syncColor: '#00FFFF',
      chatBackground: '#0A0A0A',
      messageBubbleOwn: '#FF00FF',
      messageBubblePartner: '#1A1A1A',
    },
    chatBackgroundPattern: 'none',
  },
  
  desert: {
    id: 'desert',
    name: 'Desierto',
    emoji: '🏜️',
    isPremium: true,
    description: 'Cálido atardecer del desierto',
    colors: {
      primary: '#FF8C00',
      secondary: '#FF4500',
      accent: '#FFD700',
      gradientStart: '#FF8C00',
      gradientEnd: '#FF0000',
      background: '#FFFBEB',
      cardBackground: '#FFFFFF',
      text: '#78350F',
      textSecondary: '#92400E',
      textLight: '#FDE68A',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      heartColor: '#FF8C00',
      syncColor: '#FF4500',
      chatBackground: '#FFFBEB',
      messageBubbleOwn: '#FF8C00',
      messageBubblePartner: '#FFFFFF',
    },
    chatBackgroundPattern: 'gradient',
  },
};

// Temas gratuitos
export const FREE_THEMES: ThemeType[] = ['default', 'sunset', 'ocean', 'forest', 'lavender', 'trap'];

// Temas premium
export const PREMIUM_THEMES: ThemeType[] = [
  'cherry',
  'midnight',
  'peach',
  'galaxy',
  'aurora',
  'sakura',
  'neon',
  'desert',
];
